### PR TITLE
Document free-threading build on Nixpkgs

### PR DESCRIPTION
**Pull request by mweinelt**
Pending https://github.com/NixOS/nixpkgs/pull/326919

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @mweinelt, great to see Nix packages! The cached packages haven't appeared yet in that link, I assume that's why this PR is still draft?

**Comment by mweinelt** [comment]
Yes, exactly. I expect they'll manifest in the next few hours.

**Comment by mweinelt** [comment]
Okay, looks like we got it cached. Only search.nixos.org is a bit behind, but that'll solve itself in a few hours.

```
❯ nix run nixpkgs#python313FreeThreading
Python 3.13.0b3 experimental free-threading build (main, Jun 27 2024, 13:06:51) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Review by rgommers — APPROVED** [review]
Great, thanks @mweinelt

**Pull request merged**
