### PR TITLE
Add code examples for Py_mod_gil slot and PyUnstable_Module_SetGIL

### PR DESCRIPTION
**Pull request by lysnikolaou**

### CODE REVIEW

**Review by ngoldbaum — APPROVED** [review]
Thanks for adding this!

**Comment by rgommers** [comment]
Nice, thanks @lysnikolaou. It looks like the single-phase init code can be used unconditionally (since it's guarded by `Py_GIL_Disabled`), but the multi-phase version needs a `#if PY_VERSION_HEX ...` guard - perhaps worth adding?

**Comment by lysnikolaou** [comment]
That's a good point. Maybe it's better to guard that with `Py_GIL_DISABLED` as well then?

**Comment by rgommers** [comment]
> Maybe it's better to guard that with `Py_GIL_DISABLED` as well then?

That should work too - whichever one seems cleaner. The `Py_mod_gil` slot always exists on 3.13, but I'm not sure if it matters whether it's used for the default build or not.

**Comment by lysnikolaou** [comment]
It doesn't have an effect on the free-threaded build. It still seems clearer to me to guard it with `#ifdef Py_GIL_DISABLED`. I'll open a PR.

**Pull request merged**
