### PR TITLE
Added info about special name of free-threaded Python binary on Windows

### PR DESCRIPTION
**Pull request by jimkring**

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Thanks @jimkring! Good idea to add a note about binary naming on this page.

The current note is specific to the `python.org` Windows installer, and won't be correct for (for example) the Conda installer. Also, `python3.13t` may need to be used on other platforms too, depending if the install method. So what do you think about saying something like:

_The free-threaded Python executable will always have a `python3.13t` alias (for Python 3.13); whether `python` and `python3.13` point at the free-threaded executable or not depends on the installation method (see [installing_cpython.md] for more details)._

_For example, the Python 3.13 Windows installer from `python.org` ...._

**Comment by jimkring** [comment]
@rgommers your suggestion works for me. Feel free to tweak it as you see fit. Thanks for all your work on this great resource!

**Comment by rgommers** [comment]
Updated now, thanks @jimkring

**Comment by jimkring** [comment]
Fantastic! Thanks for making those tweaks.

**Pull request merged**
