### PR TITLE
tracking: add wrapt

### PR DESCRIPTION
**Pull request by FFY00**
First supported PyPI release: https://pypi.org/project/wrapt/1.17.0.dev3/#files
CI tests: https://github.com/GrahamDumpleton/wrapt/blob/1a6b4680cba43c28f991149800249ec9f3089e26/.github/workflows/main.yml#L48-L74

### CODE REVIEW

**Review by lysnikolaou — COMMENTED** [review]
One question only: Is 1.17.0.**dev3** supposed to be a final release?

**Comment by FFY00** [comment]
No, it's a development release. I didn't see any documentation regarding the releases having to be final, that's why I opened the PR.

**Comment by lysnikolaou** [comment]
Yeah, it's okay for now since there's wheels on PyPI. We can edit it out afterwards, if there's a final release with free-threaded wheels.

**Comment by lysnikolaou** [comment]
Thanks @FFY00!

**Pull request merged**
